/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nba.rumble;

import java.awt.*;
import javax.swing.*;

public class BackstoryScreen extends javax.swing.JPanel {

    private JLabel lblCharacterName;
    private JLabel lblCharacterImage;
    private JTextArea txtBackstory;

    public BackstoryScreen() {
        initComponents();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
private void setupUI() {
    setLayout(new BorderLayout(10, 10));
    setBackground(new Color(30, 30, 35, 235));
    setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new Color(180, 180, 190), 3, true),
        BorderFactory.createEmptyBorder(15, 15, 15, 15)
    ));
    setOpaque(true);
    setVisible(false);

    // ── TOP: Image + Name ──────────────────────────────────────
    JPanel topPanel = new JPanel(new BorderLayout(12, 15));
    topPanel.setOpaque(false);
    topPanel.setPreferredSize(new Dimension(430, 190));

    lblCharacterImage = new JLabel();
    lblCharacterImage.setHorizontalAlignment(JLabel.CENTER);
    lblCharacterImage.setPreferredSize(new Dimension(110, 130));
    lblCharacterImage.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new Color(180, 180, 190), 2, true),
        BorderFactory.createLineBorder(new Color(60, 60, 70), 2, true)
    ));
    topPanel.add(lblCharacterImage, BorderLayout.WEST);

    JPanel namePanel = new JPanel(new GridBagLayout());
    namePanel.setOpaque(false);
    namePanel.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(100, 100, 110)),
        BorderFactory.createEmptyBorder(0, 0, 0, 0)
    ));

    JLabel lblBadge = new JLabel("NBA RUMBLE ");
    lblBadge.setFont(new Font("Segoe UI", Font.BOLD, 14));
    lblBadge.setForeground(new Color(180, 180, 190));
    lblBadge.setHorizontalAlignment(JLabel.CENTER);

    lblCharacterName = new JLabel("");
    lblCharacterName.setFont(new Font("Segoe UI Black", Font.BOLD, 22));
    lblCharacterName.setForeground(new Color(240, 240, 245));
    lblCharacterName.setHorizontalAlignment(JLabel.CENTER);

    // Small decorative tag under the name
    JLabel lblTag = new JLabel("[ SELECT YOUR FIGHTER ]");
    lblTag.setFont(new Font("Segoe UI", Font.ITALIC, 10));
    lblTag.setForeground(new Color(130, 130, 140));
    lblTag.setHorizontalAlignment(JLabel.CENTER);

    GridBagConstraints gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.insets = new Insets(0, 0, 0, 0);
    namePanel.add(lblBadge, gbc);
    gbc.gridy = 1;
    gbc.insets = new Insets(0, 0, 0, 0);
    namePanel.add(lblCharacterName, gbc);
    gbc.gridy = 2;
    gbc.insets = new Insets(0, 0, 0, 0);
    namePanel.add(lblTag, gbc);

    topPanel.add(namePanel, BorderLayout.CENTER);
    add(topPanel, BorderLayout.NORTH);

    // ── BOTTOM: Backstory ───────────────────────────────────────
    JPanel storyPanel = new JPanel(new BorderLayout(0, 0));
    storyPanel.setOpaque(false);

    JLabel lblStoryHeader = new JLabel("BACKSTORY");
    lblStoryHeader.setFont(new Font("Segoe UI", Font.BOLD, 11));
    lblStoryHeader.setForeground(new Color(180, 180, 190));
    lblStoryHeader.setBackground(new Color(50, 50, 58));
    lblStoryHeader.setOpaque(true);
    lblStoryHeader.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
    storyPanel.add(lblStoryHeader, BorderLayout.NORTH);

    txtBackstory = new JTextArea();
    txtBackstory.setFont(new Font("Segoe UI", Font.PLAIN, 11));
    txtBackstory.setForeground(new Color(200, 200, 205));
    txtBackstory.setBackground(new Color(22, 22, 28));
    txtBackstory.setWrapStyleWord(true);
    txtBackstory.setLineWrap(true);
    txtBackstory.setEditable(false);
    txtBackstory.setBorder(BorderFactory.createEmptyBorder(6, 8, 6, 8));

    JScrollPane scroll = new JScrollPane(txtBackstory);
    scroll.setBorder(BorderFactory.createLineBorder(new Color(80, 80, 90), 1));
    scroll.setOpaque(false);
    scroll.getViewport().setOpaque(false);

    // Style the scrollbar
    scroll.getVerticalScrollBar().setBackground(new Color(40, 40, 48));
    scroll.getVerticalScrollBar().setForeground(new Color(120, 120, 130));

    storyPanel.add(scroll, BorderLayout.CENTER);

    add(storyPanel, BorderLayout.CENTER);
}

    public void showCharacterInfo(String name, String imagePath,
        String backstory, Class<?> resourceClass) {
        lblCharacterName.setText(name);
        txtBackstory.setText(backstory);
        txtBackstory.setCaretPosition(0);

        if (imagePath != null) {
            try {
                ImageIcon icon = new ImageIcon(resourceClass.getResource(imagePath));
                Image img = icon.getImage().getScaledInstance(160, 210, Image.SCALE_DEFAULT);
                lblCharacterImage.setIcon(new ImageIcon(img));
            } catch (Exception ex) {
                lblCharacterImage.setIcon(null);
            }
        }

        setVisible(true);
        repaint();
    }

    public void hidePanel() {
        setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
