/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nba.rumble;

import java.awt.Image;
import javax.swing.ImageIcon;
import Characters.CharacterLogicClasses.Character;
/**
 *
 * @author lario
 */
public class FightScreen extends javax.swing.JFrame {
    
    private Character player1Character;
    private Character player2Character;
    
    public FightScreen(Character p1, Character p2){
        initComponents();
        
        this.player1Character = p1;
        this.player2Character = p2;
        
        setCharacterImages();
        
        //Player 1 stats.
        //Set Health value for the Health Bar
        pbHealthPlayer1.setMaximum(player1Character.getMaxHp());
        pbHealthPlayer1.setValue(player1Character.getHp());
        
        //Set Stamina value for the Stamina Bar
        pbStaminaPlayer1.setMaximum(player1Character.getMaxStamina());
        pbStaminaPlayer1.setValue(player1Character.getStamina());

        //Player 2 stats.
        //Set Health value for the Health Bar
        pbHealthPlayer2.setMaximum(player2Character.getMaxHp());
        pbHealthPlayer2.setValue(player2Character.getHp());
        
        //Set Stamina value for the Stamina Bar
        pbStaminaPlayer2.setMaximum(player2Character.getMaxStamina());
        pbStaminaPlayer2.setValue(player2Character.getStamina());
        
   
    }
    
    /**
     * Creates new form FightScreen
     */
    
    private boolean isPlayer1Turn = true;
    
    
    private void updateBars(){
        
        //player 1 update GUI bar
        pbHealthPlayer1.setValue(player1Character.getHp());
        pbStaminaPlayer1.setValue(player1Character.getStamina());
        
        
        //player 2 update GUI bar
        pbHealthPlayer2.setValue(player2Character.getHp());
        pbStaminaPlayer2.setValue(player2Character.getStamina());
        
        
    }
    private void setCharacterImages() {
        // Player 1
        ImageIcon icon1 = new ImageIcon(getClass().getResource(player1Character.getImagePath()));
        lblPlayer1Character.setIcon(icon1); // JLabel for Player 1

        // Player 2
        ImageIcon icon2 = new ImageIcon(getClass().getResource(player2Character.getImagePath()));
        lblPlayer2Character.setIcon(icon2); // JLabel for Player 2
    }
    
    
    public FightScreen() {
        initComponents();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbHealthPlayer1 = new javax.swing.JProgressBar();
        pbStaminaPlayer1 = new javax.swing.JProgressBar();
        pbStaminaPlayer2 = new javax.swing.JProgressBar();
        pbHealthPlayer2 = new javax.swing.JProgressBar();
        btnSkill1Player1 = new javax.swing.JButton();
        btnSkill3Player1 = new javax.swing.JButton();
        btnSkill2Player1 = new javax.swing.JButton();
        btnSkill1Player2 = new javax.swing.JButton();
        btnSkill2Player2 = new javax.swing.JButton();
        btnSkill3Player2 = new javax.swing.JButton();
        lblPlayer1Character = new javax.swing.JLabel();
        lblPlayer2Character = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pbHealthPlayer1.setStringPainted(true);
        getContentPane().add(pbHealthPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 400, 60));

        pbStaminaPlayer1.setStringPainted(true);
        getContentPane().add(pbStaminaPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 400, 60));

        pbStaminaPlayer2.setStringPainted(true);
        getContentPane().add(pbStaminaPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 120, 400, 60));

        pbHealthPlayer2.setStringPainted(true);
        getContentPane().add(pbHealthPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 50, 400, 60));

        btnSkill1Player1.setText("Skill 1");
        btnSkill1Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkill1Player1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkill1Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 830, 120, 90));

        btnSkill3Player1.setText("Skill 3");
        btnSkill3Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkill3Player1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkill3Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 830, 120, 90));

        btnSkill2Player1.setText("Skill 2");
        btnSkill2Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkill2Player1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkill2Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 830, 120, 90));

        btnSkill1Player2.setText("Skill 1");
        btnSkill1Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkill1Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkill1Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 830, 120, 90));

        btnSkill2Player2.setText("Skill 2");
        btnSkill2Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkill2Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkill2Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 830, 120, 90));

        btnSkill3Player2.setText("Skill 3");
        btnSkill3Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkill3Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkill3Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 830, 120, 90));

        lblPlayer1Character.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        getContentPane().add(lblPlayer1Character, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 440, 430));

        lblPlayer2Character.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        getContentPane().add(lblPlayer2Character, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 260, 440, 430));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/SelectScreenCharacters.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkill1Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill1Player1ActionPerformed
        // TODO add your handling code here:
        player1Character.useSkill1(player2Character);
        updateBars();
    }//GEN-LAST:event_btnSkill1Player1ActionPerformed

    private void btnSkill3Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill3Player1ActionPerformed
        // TODO add your handling code here:
       player1Character.useSkill3(player2Character);
        updateBars();
    }//GEN-LAST:event_btnSkill3Player1ActionPerformed

    private void btnSkill2Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill2Player1ActionPerformed
        // TODO add your handling code here:
        player1Character.useSkill2(player2Character);
        updateBars();
    }//GEN-LAST:event_btnSkill2Player1ActionPerformed

    private void btnSkill1Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill1Player2ActionPerformed
        // TODO add your handling code here:
        player2Character.useSkill1(player1Character);
        updateBars();
    }//GEN-LAST:event_btnSkill1Player2ActionPerformed

    private void btnSkill2Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill2Player2ActionPerformed
        // TODO add your handling code here:
        player2Character.useSkill2(player1Character);
        updateBars();
    }//GEN-LAST:event_btnSkill2Player2ActionPerformed

    private void btnSkill3Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill3Player2ActionPerformed
        // TODO add your handling code here:
        player2Character.useSkill3(player1Character);
        updateBars();
    }//GEN-LAST:event_btnSkill3Player2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FightScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FightScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FightScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FightScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FightScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkill1Player1;
    private javax.swing.JButton btnSkill1Player2;
    private javax.swing.JButton btnSkill2Player1;
    private javax.swing.JButton btnSkill2Player2;
    private javax.swing.JButton btnSkill3Player1;
    private javax.swing.JButton btnSkill3Player2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblPlayer1Character;
    private javax.swing.JLabel lblPlayer2Character;
    private javax.swing.JProgressBar pbHealthPlayer1;
    private javax.swing.JProgressBar pbHealthPlayer2;
    private javax.swing.JProgressBar pbStaminaPlayer1;
    private javax.swing.JProgressBar pbStaminaPlayer2;
    // End of variables declaration//GEN-END:variables
}
