/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nba.rumble;
import javax.swing.*;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
 
 
/**
*
* @author lario
*/
public class IntroScreen extends javax.swing.JFrame {
 
    /**
     * Creates new form IntroScreen
     */
    public IntroScreen() {
        initComponents();
        //to make it fullscreen 
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon pic = new ImageIcon(getClass().getResource("/Backgrounds//introscreen.gif"));
        Image img = pic.getImage().getScaledInstance(lblintroscreen.getWidth(), lblintroscreen.getHeight(), Image.SCALE_DEFAULT);
        lblintroscreen.setIcon(new ImageIcon(img));
        //add click listener to whole screen
        getContentPane().addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                goToTitleScreen();
            }
        });
    }
    //implement function to go to titlescreen
    private void goToTitleScreen(){
        TitleScreen obj = new TitleScreen();
        obj.setLocation(this.getLocation());
        obj.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblintroscreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblintroscreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/introscreen.gif"))); // NOI18N
        lblintroscreen.setMaximumSize(new java.awt.Dimension(1920, 1080));
        lblintroscreen.setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(lblintroscreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblintroscreen;
    // End of variables declaration//GEN-END:variables
}
