/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nba.rumble;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author lario
 */
public class MenuScreen extends javax.swing.JFrame {
    
    
    private AboutScreen aboutScreen = null;
    
    /**
     * Creates new form MenuScreen
     */
    public MenuScreen() {
        initComponents();
        
        ImageIcon menuScreen = new ImageIcon(getClass().getResource("/Backgrounds/mainmenu.png"));
        Image menuscreen = menuScreen.getImage().getScaledInstance(lblMenuScreen.getWidth(), lblMenuScreen.getHeight(), Image.SCALE_DEFAULT);
        lblMenuScreen.setIcon(new ImageIcon(menuscreen)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPVP = new javax.swing.JButton();
        btnPVE = new javax.swing.JButton();
        btnArcade = new javax.swing.JButton();
        AboutButton = new javax.swing.JButton();
        lblMenuScreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPVP.setText("PVP");
        btnPVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPVPActionPerformed(evt);
            }
        });
        getContentPane().add(btnPVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 720, 440, 190));

        btnPVE.setText("PVE");
        btnPVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPVEActionPerformed(evt);
            }
        });
        getContentPane().add(btnPVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 730, 440, 190));

        btnArcade.setText("Arcade");
        btnArcade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArcadeActionPerformed(evt);
            }
        });
        getContentPane().add(btnArcade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 730, 440, 190));

        AboutButton.setBackground(new java.awt.Color(102, 102, 102));
        AboutButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        AboutButton.setForeground(new java.awt.Color(255, 255, 255));
        AboutButton.setText("ABOUT");
        AboutButton.setBorder(null);
        AboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AboutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 10, 70, 30));

        lblMenuScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/mainmenu.png"))); // NOI18N
        lblMenuScreen.setMaximumSize(new java.awt.Dimension(1920, 1080));
        lblMenuScreen.setMinimumSize(new java.awt.Dimension(1920, 1080));
        lblMenuScreen.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(lblMenuScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPVPActionPerformed
        //PRIME
        this.dispose(); // Closes the MenuScreen to prevent duplicates immediately
        
        CharacterSelectScreen screen = new CharacterSelectScreen();
        screen.setVisible(true);
        screen.showModePanel("PVP");
    }//GEN-LAST:event_btnPVPActionPerformed

    private void btnPVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPVEActionPerformed
        //PRIME
        this.dispose(); // Closes the MenuScreen to prevent duplicates immediately
        
        CharacterSelectScreen screen = new CharacterSelectScreen();
        screen.setVisible(true);
        screen.showModePanel("PVE");
    }//GEN-LAST:event_btnPVEActionPerformed

    private void btnArcadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArcadeActionPerformed
        //PRIME
        this.dispose(); // Closes the MenuScreen to prevent duplicates immediately
        
        CharacterSelectScreen screen = new CharacterSelectScreen();
        screen.setVisible(true);
        screen.showModePanel("Arcade");
        
        
    }//GEN-LAST:event_btnArcadeActionPerformed

    private void AboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutButtonActionPerformed
        // TODO add your handling code here:
        
            if (aboutScreen == null || !aboutScreen.isVisible()) {
            aboutScreen = new AboutScreen();
            aboutScreen.setVisible(true);
        } else {
        
        aboutScreen.toFront();
        }

    }//GEN-LAST:event_AboutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutButton;
    private javax.swing.JButton btnArcade;
    private javax.swing.JButton btnPVE;
    private javax.swing.JButton btnPVP;
    private javax.swing.JLabel lblMenuScreen;
    // End of variables declaration//GEN-END:variables
}
