/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nba.rumble;

/**
 *
 * @author Prime
 */
public class UserInputScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserInputScreen.class.getName());

    /**
     * Creates new form UserInputScreen
     */
    public UserInputScreen() {
        initComponents();
        
        // This single line perfectly centers the window on ANY monitor
        this.setLocationRelativeTo(null);
        
        // --- ADDING BACKGROUND IMAGE (PRIME) ---
        // 1. Point to the correct folder path starting with a forward slash "/"
        javax.swing.ImageIcon bgIcon = new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/SelectScreenCharacters.png"));
        
        // 2. Scale the image to perfectly fit the label's width and height
        java.awt.Image scaledImg = bgIcon.getImage().getScaledInstance(400, 300, java.awt.Image.SCALE_DEFAULT);
        
        // 3. Set the scaled image to your background label
        lblBackground.setIcon(new javax.swing.ImageIcon(scaledImg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeTitle = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Input");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeTitle.setText("Welcome, Baller!");
        getContentPane().add(welcomeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 32, -1, 27));

        txtPassword.setText("Enter Password");
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 188, 202, 37));

        txtUsername.setText("Enter Username");
        txtUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 115, 202, 37));

        submitBtn.setBackground(new java.awt.Color(102, 255, 102));
        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(0, 0, 0));
        submitBtn.setText("Submit");
        submitBtn.setActionCommand("Submit");
        submitBtn.addActionListener(this::submitBtnActionPerformed);
        getContentPane().add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 243, -1, -1));

        clearBtn.setBackground(new java.awt.Color(204, 0, 0));
        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.setToolTipText("");
        clearBtn.addActionListener(this::clearBtnActionPerformed);
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 243, -1, -1));

        usernameLabel.setText("Username:");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 93, -1, -1));

        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 166, -1, -1));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 410, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        
        String username = txtUsername.getText();
        String password = txtPassword.getText(); 
        
//        FILEREADING AND FILEWRITING APPLIED HERE (PRIME)
        
        // 1. Prevent them from submitting the placeholder text or blank fields
        if (username.equals("Enter Username") || password.equals("Enter Password") || username.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid Username and Password.", "Wait up!", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Stops the code here
        }

        boolean userExists = false;
        boolean loginSuccess = false;

        // 2. Check if the user already exists (Login Attempt)
        try {
            java.io.File file = new java.io.File("users.txt");
            if (file.exists()) {
                java.util.Scanner scanner = new java.util.Scanner(file);
                while (scanner.hasNextLine()) {
                    String line = scanner.nextLine();
                    String[] userData = line.split(",");
                    
                    // Check if the username matches the first column in our text file
                    if (userData.length >= 2 && userData[0].equals(username)) {
                        userExists = true;
                        // Check if the password matches
                        if (userData[1].equals(password)) {
                            loginSuccess = true;
                        }
                        break; // Stop searching once we find the username
                    }
                }
                scanner.close();
            }
        } catch (java.io.FileNotFoundException e) {
            System.out.println("No database found, creating a new one...");
        }

        // 3. Process the Results
        if (userExists) {
            if (loginSuccess) {
                // Successful Login!
                javax.swing.JOptionPane.showMessageDialog(this, "Welcome back to the court, " + username + "!");
                new IntroScreen().setVisible(true); // Open Main Menu
                this.dispose(); // Close this screen
            } else {
                // Wrong Password
                javax.swing.JOptionPane.showMessageDialog(this, "Incorrect password! Try again.", "Login Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // 4. User does not exist, so automatically Register them!
            try {
                java.io.FileWriter writer = new java.io.FileWriter("users.txt", true);
                writer.write(username + "," + password + ",0\n"); // Adds them with a starting score of 0
                writer.close();
                
                javax.swing.JOptionPane.showMessageDialog(this, "New account created! Welcome to NBA Rumble, " + username + "!");
                new IntroScreen().setVisible(true); // Open Main Menu
                this.dispose(); // Close this screen
                
            } catch (java.io.IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error saving account data.", "System Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserInputScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeTitle;
    // End of variables declaration//GEN-END:variables
}
