/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nba.rumble;

/**
 *
 * @author Prime
 */
public class UserInputScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserInputScreen.class.getName());

    /**
     * Creates new form UserInputScreen
     */
    public UserInputScreen() {
        initComponents();
        
        // This single line perfectly centers the window on ANY monitor
        this.setLocationRelativeTo(null);
        
        // --- ADDING BACKGROUND IMAGE (PRIME) ---
        // 1. Point to the correct folder path starting with a forward slash "/"
        javax.swing.ImageIcon bgIcon = new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/SelectScreenCharacters.png"));
        
        // 2. Scale the image to perfectly fit the label's width and height
        java.awt.Image scaledImg = bgIcon.getImage().getScaledInstance(400, 300, java.awt.Image.SCALE_DEFAULT);
        
        // 3. Set the scaled image to your background label
        lblBackground.setIcon(new javax.swing.ImageIcon(scaledImg));
    }
    
    private void registerNewUser(String user, String pass) {
        try (java.io.PrintWriter out = new java.io.PrintWriter(new java.io.BufferedWriter(new java.io.FileWriter("users.txt", true)))) {
            // Format: Username,Password,Score (Defaults to 0)
            out.println(user + "," + pass + ",0");
            javax.swing.JOptionPane.showMessageDialog(this, "Account created! Good luck on the court, " + user + ".");
            proceedToGame();
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error saving account.", "System Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void proceedToGame() {
        new IntroScreen().setVisible(true);
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeTitle = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Input");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeTitle.setText("Welcome, Baller!");
        getContentPane().add(welcomeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 32, -1, 27));

        txtPassword.setText("Enter Password");
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 188, 202, 37));

        txtUsername.setText("Enter Username");
        txtUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 115, 202, 37));

        submitBtn.setBackground(new java.awt.Color(102, 255, 102));
        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(0, 0, 0));
        submitBtn.setText("Submit");
        submitBtn.setActionCommand("Submit");
        submitBtn.addActionListener(this::submitBtnActionPerformed);
        getContentPane().add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 243, -1, -1));

        clearBtn.setBackground(new java.awt.Color(204, 0, 0));
        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.setToolTipText("");
        clearBtn.addActionListener(this::clearBtnActionPerformed);
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 243, -1, -1));

        usernameLabel.setText("Username:");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 93, -1, -1));

        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 166, -1, -1));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 410, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String username = txtUsername.getText().trim();
        String password = txtPassword.getText().trim(); 
        
        // 1. Basic Validation
        if (username.isEmpty() || username.equals("Enter Username") || 
            password.isEmpty() || password.equals("Enter Password")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Fields cannot be empty!", "NBA Rumble", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean usernameExists = false;
        boolean exactMatch = false;

        // 2. Check users.txt for existing records
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("users.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length >= 2) {
                    String storedUser = data[0].trim();
                    String storedPass = data[1].trim();

                    if (storedUser.equalsIgnoreCase(username)) {
                        usernameExists = true;
                        if (storedPass.equals(password)) {
                            exactMatch = true;
                        }
                        break; // Stop searching once username is found
                    }
                }
            }
        } catch (java.io.IOException e) {
            // If file doesn't exist yet, we just proceed to registration
            logger.log(java.util.logging.Level.INFO, "Database file not found. A new one will be created.");
        }

        // 3. Process Branching Logic
        if (exactMatch) {
            // SUCCESSFUL LOGIN: Pair exists in file
            javax.swing.JOptionPane.showMessageDialog(this, "Welcome back, " + username + "!");
            proceedToGame();
        } else if (usernameExists) {
            // USERNAME TAKEN: Username found but password was different
            javax.swing.JOptionPane.showMessageDialog(this, "Username already taken! Please check your password.", "Login Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            // NEW SIGNUP: Username not found at all
            registerNewUser(username, password);
        }
    }//GEN-LAST:event_submitBtnActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserInputScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeTitle;
    // End of variables declaration//GEN-END:variables
}
